Tests_task:
  # Run tests on macOS Mojave:
  osx_instance:
    image: mojave-xcode-10.1

  # Don't run on Python2 branch:
  only_if: $CIRRUS_BRANCH != 'python-2-supported'

  # Do not skip if new commits are pushed to master:
  auto_cancellation: $CIRRUS_BRANCH != 'master'

  # Install Python3 and NodeJS:
  brew_cache:
    folder: ~/Library/Caches/Homebrew
    populate_script:
      - brew install node
      - brew install python@3

  # Install test dependencies:
  Install_Test_Dependencies_script:
    - python3 -m pip install -r $CIRRUS_WORKING_DIR/requirements/test.txt
    - python3 -m pip install -r $CIRRUS_WORKING_DIR/requirements/dev.txt
    - npm install markdown-link-check@3.7.2
    - npm install markdownlint-cli

  # Install new beta build:
  Install_Beta_Build_script:
    - make beta

  # Test the Python code:
  Run_Python_Tests_script:
    - make test
    - make safetyci

  # Lint Markdown:
  Markdown_Tests_script:
    - make markdownlint
    - markdown-link-check *.md
