container:
  image: python:latest

MarkdownTests_task:
  container:
    image: node:latest
  only_if: $CIRRUS_BRANCH != 'python-2-supported'
  auto_cancellation: $CIRRUS_BRANCH != 'master'
  # Install Markdown linter:
  InstallLinter_script:
    - make installmdlint
  # Install Markdown link checker:
  InstallLinkChecker_script:
    - make installlinkcheck
  # Lint Markdown:
  MarkdownLint_script:
    - markdownlint --config=.markdownlint.yml *.md
    - markdownlint --config=.markdownlint.yml .github/*.md
    - markdownlint --config=.markdownlint.yml .github/ISSUE_TEMPLATE/*.md
    - markdownlint --config=.markdownlint.yml extras/*.md
  # Check links:
  LinkCheck_script:
    - make linkcheck

task:
  name: CodeTests
  only_if: $CIRRUS_BRANCH != 'python-2-supported'
  auto_cancellation: $CIRRUS_BRANCH != 'master'
  # Clean workspace:
  CleanWorkspace_script:
    - make clean
  # Install test dependencies:
  InstallTestDependencies_script:
    - make testrequirements
    - make devrequirements
  # Build the package:
  BuildPackage_script:
    - make dist
  # Install new beta build:
  InstallBetaBuild_script:
    - make beta
  # Test the code:
  RunTests_script:
    - make test
  PyDocStyle_script:
    - make pydocstyle
  PyCodeStyle_script:
    - make pycodestyle
  Flake8Style_script:
    - make flake8
  PylintStyle_script:
    - make pylint
  DependencySecurityTest_script:
    - make safetyci
