task:
  # Task name:
  name: Tests

  # Run tests on macOS Mojave:
  osx_instance:
    image: mojave-xcode-10.1

  # Don't run on Python2 branch:
  only_if: $CIRRUS_BRANCH != 'python-2-supported'

  # Do not skip if new commits are pushed to master:
  auto_cancellation: $CIRRUS_BRANCH != 'master'

  # Install test dependencies:
  Install_Test_Dependencies_script:
    # Install Python3 and NodeJS:
    - brew install node
    - brew install python@3
    # Install Python dependencies:
    - python3 -m pip install -r $CIRRUS_WORKING_DIR/requirements/test.txt
    - python3 -m pip install -r $CIRRUS_WORKING_DIR/requirements/dev.txt
    # Install NodeJS dependencies:
    - npm install -g markdown-link-check@3.7.2
    - npm install -g markdownlint-cli

  # Install new beta build:
  Install_Beta_Build_script:
    - make beta

  # Test the Python code:
  Run_Python_Tests_script:
    # Set target:
    - export TARGET=code
    # Run tests:
    - make test

  # Lint Markdown files:
  Run_Markdown_Tests_script:
    # Set target:
    - export TARGET=markdown
    # Run tests:
    - make test
